### PR TITLE
current clamp + MembraneReport

### PR DESCRIPTION
**Pull request by latimerb**
updated current clamp module to accept gids (small bug in previous commit) and updated MembraneReport class to accept gids so that the user can record the membrane potential of a handful of cells instead of all of them

### CODE REVIEW

**Comment by pgleeson** [comment]
@kaeldai I believe some of these change are required to get the Sonata examples working again with BMTK.

@latimerb have you tested these changes with all of the examples here, as well as the Sonata example networks, e.g. https://github.com/AllenInstitute/sonata/tree/master/examples/5_cells_iclamp?

**Comment by latimerb** [comment]
@pgleeson I tested with the Jupyter notebook tutorials but not with the Sonata examples. I'm not familiar with Sonata but I will give it a try and let you know if it works.

**Comment by latimerb** [comment]
@pgleeson @kaeldai OK, I tested it with the Sonata examples and made a small tweak. Now users can specify the node_set to be stimulated, as they do in the Sonata examples. Alternatively, users may specify specific gids to be stimulated. 

In order to plot the output of the 5_cells_iclamp Sonata example, this change needs to be made:
https://github.com/AllenInstitute/sonata/pull/116

The example runs without the change, it is only for visualizing the output. I also double-checked the BMTK examples, they also work with this change.

**Comment by pgleeson** [comment]
Thanks @latimerb. I think a similar update is required in https://github.com/AllenInstitute/bmtk/blob/develop/bmtk/simulator/pointnet/pointsimulator.py#L145, as the example at https://github.com/AllenInstitute/bmtk/tree/develop/docs/examples/point_iclamp is broken. 

This should fix the issues with the other Sonata simulation test examples e.g. https://github.com/AllenInstitute/sonata/tree/master/examples/sim_tests/intfire/ten_cells_iclamp_nest

There are also some changes here: https://github.com/AllenInstitute/sonata/commit/b94c27be8413c12c3a67616c6b1116e6a83fdb0f for Sonata examples. I'll open a PR with these @kaeldai when they all work locally. 

Note this script can be used to test most of the sonata examples: https://github.com/AllenInstitute/sonata/blob/master/examples/test.sh

**Pull request merged**
