### PR TITLE
update location of demo files

### PR DESCRIPTION
**Pull request by VBaratham**

### CODE REVIEW

**Review by nicain — APPROVED** [review]
LGTM.  @kaeldai are there tests that can smoke-check the location of these files?

**Comment by nicain** [comment]
@VBaratham Since your in it right now, can you add a test that will expose the error you are correcting, to make sure it doesn't happen again?

**Comment by VBaratham** [comment]
@nicain I took a quick look and couldn't find a way to implement tests for these things. If anyone has suggestions I'd be happy to do it.

I did find another outdated path, which I just updated. Sorry for updating the PR after approval (x2), I'll stop now!

**Comment by nicain** [comment]
It is no problem at all to update a PR approval, thanks for contributing!!  How did you happen to come across the issue?  Is there an AllenInstitute/bmtk issue that this PR is resolving?

**Comment by VBaratham** [comment]
Thanks. I am playing around with bmtk for the first time, and noticed these on https://alleninstitute.github.io/bmtk/bionet.html. AFAIK there is no issue related to this

**Comment by nicain** [comment]
OK sounds good, no test necessary then (souds like purely a documentation issue then). Ill let the lead dev do the merge.

**Pull request closed without merging**
