### PR TITLE
Rename bmtk/builder/aux folder to auxi for Windows

### PR DESCRIPTION
**Pull request by tjbanks**
Renaming this aux folder to auxi allows for Windows users to pull down the repository. Aux is forbidden folder name in Windows -- https://social.technet.microsoft.com/Forums/ie/en-US/d1cf7394-a39b-46bf-823d-46f33b2f78d0/unable-to-create-folder-named-quotauxquot-anywhere-in-the-disk?forum=w7itprogeneral 

I searched through the repository using the following to find all references before committing. 
`grep -rnw '.' -e 'aux'`

### CODE REVIEW

**Comment by kaeldai** [comment]
hi @tjbanks 
This is great. I'm going to merge the PR, however I noticed in BioAxonStub.hoc you added 
```
load('import3d.hoc')
```
But when I run it NEURON throws a hoc error, it shouldn't be able to find the hoc file and import3d/ directory. Is there a reason you added the load('import3d.hoc') command, if so it should be easy for me to update the directory structure. Otherwise I can just pull the other files and leave BioAxonStub.hoc alone.

**Comment by tjbanks** [comment]
@kaeldai --
Didn't mean for that to make it in, I apologize. 

There may have been something weird going on with my setup or for Windows in general. I think I was unable to find `Import3d_SWC_read` or `Import3d_GUI` without the load statement. Definitely unrelated to the aux issue.

**Comment by kaeldai** [comment]
No worries! Unfortunatly we haven't done very much testing of the bmtk with Windows, but I will see if I get similar issues on my windows machine. Are you using anaconda or just the standard python install?

**Comment by tjbanks** [comment]
Very cool, thank you! Anaconda here. 

Aside from that one import I was able to get output results just fine running through the demos/tutorials. This is a great project.

**Comment by latimerb** [comment]
Hi @kaeldai, were you able to try installation on Windows? We're still running into a myriad of errors. Several of us are interested in getting this going so if you could let us know that would be great!

**Pull request merged**
